[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]
name = "serpmcp"
version = "0.1.0"
description = "Yet another SerpApi MCP Server"
readme = "README.md"
requires-python = ">=3.14"
license = {text = "MIT"}
dependencies = []
